apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helper
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./chart
      sourceRef:
        kind: GitRepository
        name: homelab-app-chart
        namespace: default
      interval: 1m
  values:
    replicaCount: 1
    image:
      imagePolicy: enabled
      repository: devkrolikowski/swiss-army-knife
      tag: 0.3.0 # {"$imagepolicy": "flux-system:helper:tag"}
    resources:
      limits:
        memory: "1024Mi"
        cpu: "2"
      requests:
        memory: "1024Mi"
        cpu: "1"
    ingress:
      enabled: false
    volumes:
      enabled: true
      mountPath:
        - homelab:/storage
      type:
        nfs:
          server: lab-storage.lan
          path: /volume1/warez/Backups
