apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pig-game
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./chart
      sourceRef:
        kind: GitRepository
        name: homelab-app-chart
        namespace: default
      interval: 1m
  values:
    replicaCount: 1
    database:
      enabled: false
    image:
      imagePolicy: true
      repository: gitea.angrybits.pl/kkrolikowski/pig-game
      tag: 0.0.1 # {"$imagepolicy": "flux-system:pig-game:tag"}
    resources:
      limits:
        memory: "128Mi"
        cpu: "50m"
      requests:
        memory: 100Mi
        cpu: 10m
    services:
      - name: http
        servicePort: 80
        targetPort: 80
    ingress:
      enabled: true
      ssl: true
      hosts:
        - host: pig-game.lab.angrybits.pl
      tls:
        - hosts:
            - pig-game.lab.angrybits.pl
    volumes:
      enabled: false
    deployNotifications:
      enabled: true
      image: gitea.angrybits.pl/kkrolikowski/mattermost-notify:0.0.3
