# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: email-form
#   namespace: default
# spec:
#   interval: 1m
#   chart:
#     spec:
#       chart: ./chart
#       sourceRef:
#         kind: GitRepository
#         name: homelab-app-chart
#         namespace: default
#       interval: 1m
#   values:
#     replicaCount: 1
#     database:
#       enabled: false
#     image:
#       imagePolicy: true
#       repository: gitea.angrybits.pl/kkrolikowski/email-form
#       tag: 0.0.2 # {"$imagepolicy": "flux-system:email-form:tag"}
#     resources:
#       limits:
#         memory: "128Mi"
#         cpu: "50m"
#       requests:
#         memory: 100Mi
#         cpu: 10m
#     services:
#       - name: http
#         servicePort: 3000
#         targetPort: 3000
#     ingress:
#       enabled: true
#       ssl: true
#       hosts:
#         - host: testy.lab.angrybits.pl
#       tls:
#         - hosts:
#             - testy.lab.angrybits.pl
#     volumes:
#       enabled: false
#     deployNotifications:
#       enabled: true
#       image: gitea.angrybits.pl/kkrolikowski/mattermost-notify:0.0.3
