apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mattermost
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./chart
      sourceRef:
        kind: GitRepository
        name: homelab-app-chart
        namespace: default
      interval: 1m
  values:
    replicaCount: 1
    database:
      enabled: false
    image:
      imagePolicy: true
      repository: gitea.angrybits.pl/kkrolikowski/mattermost
      tag: 2.1.0 # {"$imagepolicy": "flux-system:mattermost:tag"}
    env:
      - name: MM_SQLSETTINGS_DRIVERNAME
        value: postgres
      - name: MM_SQLSETTINGS_DATASOURCE
        valueFrom:
          secretKeyRef:
            name: mattermost-secret
            key: MM_SQLSETTINGS_DATASOURCE
      - name: TZ
        value: "Europe/Warsaw"
      - name: MM_SERVICESETTINGS_SITEURL
        value: https://chat.angrybits.pl
      - name: MATTERMOST_IMAGE
        value: mattermost-team-edition
      - name: MATTERMOST_IMAGE_TAG
        value: "7.5.2"
      - name: MM_SERVICESETTINGS_LISTENADDRESS
        value: ":8080"
      - name: MM_SERVICESETTINGS_ENABLEINSECUREOUTGOINGCONNECTIONS
        value: "true"
      - name: MM_SERVICESETTINGS_ENABLEPOSTUSERNAMEOVERRIDE
        value: "true"
      - name: MM_SERVICESETTINGS_ENABLEPOSTICONOVERRIDE
        value: "true"
    resources:
      limits:
        memory: "1024Mi"
        cpu: "2"
      requests:
        memory: 256Mi
        cpu: 600m
    services:
      - name: http
        servicePort: 8080
        targetPort: 8080
    ingress:
      enabled: true
      ssl: true
      hosts:
        - host: chat.angrybits.pl
      tls:
        - hosts:
            - chat.angrybits.pl
    volumes:
      enabled: true
      mountPath:
        - data:/opt/mattermost/data
        - logs:/opt/mattermost/logs
      ownership: 1024:100
      type:
        nfs:
          server: lab-storage.lan
          path: /volume1/storagelab
