apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./chart
      sourceRef:
        kind: GitRepository
        name: homelab-app-chart
        namespace: default
      interval: 1m
  values:
    replicaCount: 1
    database:
      enabled: true
    image:
      repository: gitea/gitea
      tag: 1.19-dev-linux-arm64
    env:
      - name: USER_UID
        value: "1024"
      - name: USER_GID
        value: "100"
      - name: GITEA__database__DB_TYPE
        value: mysql
      - name: GITEA__database__HOST
        value: lab-helper.lan:3306
      - name: GITEA__database__NAME
        value: gitea
      - name: GITEA__database__USER
        valueFrom:
          secretKeyRef:
            name: gitea-db
            key: login
      - name: GITEA__database__PASSWD
        valueFrom:
          secretKeyRef:
            name: gitea-db
            key: password
      - name: GITEA__service__DISABLE_REGISTRATION
        value: "true"
      - name: GITEA__service__REQUIRE_SIGNIN_VIEW
        value: "true"
    resources:
      limits:
        memory: "2Gi"
        cpu: "2"
      requests:
        memory: 512Mi
        cpu: 500m
    services:
      - name: http
        servicePort: 80
        targetPort: 3000
      - name: ssh
        servicePort: 2222
        targetPort: 22
    ingress:
      enabled: true
      ssl: true
      hosts:
        - host: gitea.angrybits.pl
      tls:
        - hosts:
            - gitea.angrybits.pl
    volumes:
      enabled: true
      mountPath:
        - gitea:/var/lib/gitea
        - config:/etc/gitea
        - data:/data
      ownership: 1024:100
      type:
        nfs:
          server: lab-storage.lan
          path: /volume1/storagelab
