apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nodeapp
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./chart
      sourceRef:
        kind: GitRepository
        name: homelab-app-chart
        namespace: default
      interval: 1m
  values:
    replicaCount: 1
    database:
      enabled: false
    image:
      imagePolicy: true
      repository: gitea.angrybits.pl/kkrolikowski/nodeapp
      tag: 0.5.0 # {"$imagepolicy": "flux-system:nodeapp:tag"}
    resources:
      limits:
        memory: "128Mi"
        cpu: "50m"
      requests:
        memory: 100Mi
        cpu: 10m
    services:
      - name: http
        servicePort: 3000
        targetPort: 3000
    ingress:
      enabled: true
      ssl: false
      hosts:
        - host: test-nodeapp.lan
    volumes:
      enabled: false
