apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-state-metrics
  namespace: monitoring
spec:
  template:
    spec:
      containers:
        - image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.8.1
          name: kube-state-metrics
          args:
            - --resource=pods
            - --node=$(NODE_NAME)
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
