apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: gitea.angrybits.pl/kkrolikowski/backups:0.0.1
              imagePullPolicy: IfNotPresent
              command: ["/opt/app/backup.sh"]
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: dbadmin
                  key: login
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: dbadmin
                  key: password
            - name: DB_HOST
              value: lab-helper.lan
          restartPolicy: OnFailure
