apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: focalboard
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./chart
      sourceRef:
        kind: GitRepository
        name: homelab-app-chart
        namespace: default
      interval: 1m
  values:
    replicaCount: 1
    database:
      enabled: false
    image:
      imagePolicy: true
      repository: gitea.angrybits.pl/kkrolikowski/focalboard
      tag: 0.0.1 # {"$imagepolicy": "flux-system:focalboard:tag"}
    resources:
      limits:
        memory: "1024Mi"
        cpu: "2"
      requests:
        memory: 256Mi
        cpu: 600m
    services:
      - name: http
        servicePort: 8000
        targetPort: 8000
    ingress:
      enabled: true
      ssl: true
      hosts:
        - host: todo.angrybits.pl
      tls:
        - hosts:
            - todo.angrybits.pl
    volumes:
      enabled: true
      mountPath:
        - data:/var/lib/focalboard
      ownership: 1024:100
      type:
        nfs:
          server: lab-storage.lan
          path: /volume1/storagelab
