apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zattotech
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./chart
      sourceRef:
        kind: GitRepository
        name: homelab-app-chart
        namespace: default
      interval: 1m
  values:
    replicaCount: 1
    database:
      enabled: false
    image:
      imagePolicy: true
      repository: gitea.angrybits.pl/zatto/zattotech
      tag: 0.1.27 # {"$imagepolicy": "flux-system:zattotech:tag"}
    env:
      - name: DB_HOST
        valueFrom:
          secretKeyRef:
            name: zattotech-secrets
            key: DB_HOST
      - name: DB_NAME
        valueFrom:
          secretKeyRef:
            name: zattotech-secrets
            key: DB_NAME
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: zattotech-secrets
            key: DB_PASSWORD
      - name: DB_PORT
        valueFrom:
          secretKeyRef:
            name: zattotech-secrets
            key: DB_PORT
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: zattotech-secrets
            key: DB_USER
      - name: SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: zattotech-secrets
            key: SECRET_KEY
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: zattotech-secrets
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: zattotech-secrets
            key: AWS_SECRET_ACCESS_KEY
      - name: AWS_STORAGE_BUCKET_NAME
        valueFrom:
          secretKeyRef:
            name: zattotech-secrets
            key: AWS_STORAGE_BUCKET_NAME
      - name: AWS_QUERYSTRING_AUTH
        valueFrom:
          secretKeyRef:
            name: zattotech-secrets
            key: AWS_QUERYSTRING_AUTH
      - name: MYSQL_ATTR_SSL_CA
        value: "./ca-certificates.crt"
    resources:
      limits:
        memory: "1024Mi"
        cpu: "2"
      requests:
        memory: 256Mi
        cpu: 500m
    services:
      - name: http
        servicePort: 8000
        targetPort: 8000
    ingress:
      enabled: true
      ssl: true
      hosts:
        - host: zattotech.lab.angrybits.pl
      tls:
        - hosts:
            - zattotech.lab.angrybits.pl
    volumes:
      enabled: false
    deployNotifications:
      enabled: true
      image: gitea.angrybits.pl/kkrolikowski/mattermost-notify:0.0.3
