apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-2repl
  resources:
    requests:
      storage: 20Gi