apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus
  namespace: monitoring

spec:
  rules:
    - host: prometheus.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  prometheus-service
                port:
                  number: 9090