apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: topliv-manager
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./chart
      sourceRef:
        kind: GitRepository
        name: homelab-app-chart
        namespace: default
      interval: 1m
  values:
    replicaCount: 1
    database:
      enabled: false
    image:
      imagePolicy: true
      repository: gitea.angrybits.pl/zatto/manager
      tag: 0.0.1 # {"$imagepolicy": "flux-system:topliv-manager:tag"}
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: topsky-secret
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: topsky-secret
            key: AWS_SECRET_ACCESS_KEY
      - name: AWS_STORAGE_BUCKET_NAME
        valueFrom:
          secretKeyRef:
            name: topsky-secret
            key: AWS_STORAGE_BUCKET_NAME
      - name: DB_HOST
        valueFrom:
          secretKeyRef:
            name: topsky-secret
            key: DB_HOST
      - name: DB_NAME
        valueFrom:
          secretKeyRef:
            name: topsky-secret
            key: DB_NAME
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: topsky-secret
            key: DB_PASSWORD
      - name: DB_PORT
        valueFrom:
          secretKeyRef:
            name: topsky-secret
            key: DB_PORT
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: topsky-secret
            key: DB_USER
      - name: AWS_QUERYSTRING_AUTH
        value: "False"
      - name: MYSQL_ATTR_SSL_CA
        value: "/etc/ssl/certs/ca-certificates.crt"
    resources:
      limits:
        memory: "1024Mi"
        cpu: "2"
      requests:
        memory: 256Mi
        cpu: 10m
    services:
      - name: http
        servicePort: 8000
        targetPort: 8000
    ingress:
      enabled: true
      ssl: true
      hosts:
        - host: topsky.angrybits.pl
      tls:
        - hosts:
            - topsky.angrybits.pl
    volumes:
      enabled: false
