apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: www
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./chart
      sourceRef:
        kind: GitRepository
        name: homelab-app-chart
        namespace: default
      interval: 1m
  values:
    replicaCount: 1
    database:
      enabled: false
    image:
      imagePolicy: true
      repository: gitea.angrybits.pl/kkrolikowski/swimmingpoolwatcher
      tag: 0.4.0 # {"$imagepolicy": "flux-system:homer-www:tag"}
    resources:
      limits:
        memory: "256Mi"
        cpu: "200m"
      requests:
        memory: 50Mi
        cpu: 10m
    services:
      - name: http
        servicePort: 8000
        targetPort: 8000
    ingress:
      enabled: true
      ssl: false
      hosts:
        - host: basen.lan
    volumes:
      enabled: false
